---
- name: test playbook
  hosts: all
  gather_facts: yes
  connection: local
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: py platform test
      command: ls /

    - name: py2 test
      command: ls /
      vars:
        ansible_python_interpreter: /usr/bin/python2

    - name: py3 test
      command: ls /
      vars:
        ansible_python_interpreter: /usr/bin/python3
