---
- name: test playbook
  hosts: all
  gather_facts: no
  connection: local
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - name: py2 test
      command: /bin/ps ax
      vars:
        ansible_python_interpreter: /usr/bin/python2
    - name: py3 test
      command: /bin/ps axf
      vars:
        ansible_python_interpreter: /usr/bin/python3
